name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 
  dio_http_cache:
    git:
      url: https://github.com/hurshi/dio-http-cache.git
  dio_http_formatter:
  connectivity_plus: ^3.0.2
  equatable: 
  logger: 
  flutter_secure_storage: 
  loading_indicator: 
  flutter_svg: 
  flutter_screenutil:
  get_storage: 
  shimmer: 
  intl:
  path_provider:
  html: ^0.15.0
  # share:
  flutter_localizations:
    sdk: flutter
  # pdf: 
  # permission_handler: 
  # firebase_analytics: ^9.3.3
  # firebase_core: ^1.21.1
  http_parser:
  mime_type:
  
  scm_mobile_sdk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
#  assets:
#    - lang/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#  - family: SFUIText
#    fonts:
#    - asset: ../assets/fonts/SFUIText-Bold.ttf
#    - asset: ../assets/fonts/SFUIText-Light.ttf
#    - asset: ../assets/fonts/SFUIText-Regular.ttf
#  - family: SFUIDisplay
#    fonts:
#    - asset: ../assets/fonts/SFUIDisplay-Bold.otf
#    - asset: ../assets/fonts/SFUIDisplay-Light.otf
#  - family: Aclonica
#    fonts:
#    - asset: ../assets/fonts/Aclonica-Regular.ttf

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
