library core;

export 'src/animation/screen_transition/screen_transition.dart';
export 'src/navigation/navigation.dart';
export 'src/data/network/network.dart';
export 'src/extentions/extentions.dart';
export 'src/navigation/navigation.dart';
export 'src/utils/utils.dart';
export 'package:equatable/equatable.dart';
export 'package:get/utils.dart';
export 'package:loading_indicator/loading_indicator.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'src/localization/localization.dart';
export 'package:get_storage/get_storage.dart';
export 'package:intl/intl.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:dio_http_cache/dio_http_cache.dart';
export 'package:dio_http_formatter/dio_http_formatter.dart';
export 'package:http_parser/http_parser.dart';
export 'package:mime_type/mime_type.dart';
// export 'package:firebase_analytics/firebase_analytics.dart';
// export 'package:firebase_analytics/observer.dart';
// export 'package:firebase_core/firebase_core.dart';
