# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: 
          echo "CLEAN DEPENDENCY"
          cd core
          flutter clean

          cd ..
          flutter clean

          echo "[INFO] All dependencies cleansing done"
          
          echo "SYNC DEPENDENCY"
          cd core
          flutter pub get

          cd ..
          flutter pub get

          echo "[INFO] All dependencies sync done"
          
          echo "BUILD AAR"
          rm .android/build.gradle
          cp upload/project/build.gradle .android

          rm .android/Flutter/build.gradle
          cp upload/flutter/build.gradle .android/Flutter

          rm .android/app/build.gradle
          cp upload/app/build.gradle .android/app

          rm .android/app/src/main/AndroidManifest.xml
          cp upload/AndroidManifest.xml .android/app/src/main

          cp upload/google-services.json .android/app

          cp -r upload/xml .android/app/src/main/res

          flutter build aar --build-number 0.0.1
          
          echo "[INFO] Moved file done"

      - name: Step 1 - Create temporary artifacts folder
        run: mkdir downloads

      - name: Step 2 - Add artifact to publish to temp folder
        run: 
          cp -r build/host/outputs/repo downloads

      - name: Step 3 - Use the Upload artifact Github Actions
        uses: actions/upload-artifact@v3.1.1
        with:
          name: assets-for-download
          path: downloads
